### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by choucavalier** [lohedges/latuxit#1]
It would be nice to be able to easily install LaTuXiT using a homebrew formula rather than having to clone and compile by hand!

**Comment by lohedges** [comment]
Sorry for the slow response. I don't have any experience write Homebrew formulae, I'm afraid. If this is something that you are familiar with, feel free to fork the code and issue a pull request. I'm not keen on supporting OS specific package managers myself and simply provide a generic Makefile that _should_ work on any UNIX-like OS.

For reference, I believe that Homebrew now provides a `basictex` package that downloads and runs the installer for you, which would help with the `pdflatex` and `pdfcrop` dependencies. Previously this would only _download_ the installer for you. This would make a Homebrew install rather clunky, since you'd need to manually install TeX part way through. I'm also not familiar with the way in which Homebrew supports pre/post installation scripts, which would be required for the creation of the `LaTuXiT` directory.
